jets_calibration:
  collection:
    2022_preEE:
      AK8PFPuppi: "FatJet"
    2022_postEE:
      AK8PFPuppi: "FatJet"
    2023_preBPix:
      AK8PFPuppi: "FatJet"
    2023_postBPix:
      AK8PFPuppi: "FatJet"

  variations:
    full_variations: 
      AK8PFPuppi: "${default_jets_calibration.variations.full_variations.AK4PFPuppi}"

  apply_jec_MC:  # this is needed to know which collection is corrected with which jet factory
    2022_preEE: 
      AK8PFPuppi: True
    2022_postEE: 
      AK8PFPuppi: True
    2023_preBPix: 
      AK8PFPuppi: True
    2023_postBPix: 
      AK8PFPuppi: True
  
  apply_jec_Data:  # this is needed to know which collection is corrected with which jet factory
    2022_preEE: 
      AK8PFPuppi: True
    2022_postEE: 
      AK8PFPuppi: True
    2023_preBPix: 
      AK8PFPuppi: True
    2023_postBPix: 
      AK8PFPuppi: True

  apply_pt_regr_MC:
    2022_preEE: 
      AK8PFPuppi: False
    2022_postEE: 
      AK8PFPuppi: False
    2023_preBPix: 
      AK8PFPuppi: False
    2023_postBPix: 
      AK8PFPuppi: False

  apply_pt_regr_Data:
    2022_preEE: 
      AK8PFPuppi: False
    2022_postEE: 
      AK8PFPuppi: False
    2023_preBPix: 
      AK8PFPuppi: False
    2023_postBPix: 
      AK8PFPuppi: False

  apply_jec_msoftdrop_MC:
    2022_preEE:
      AK8PFPuppi: True
    2022_postEE: 
      AK8PFPuppi: True
    2023_preBPix: 
      AK8PFPuppi: True
    2023_postBPix: 
      AK8PFPuppi: True
    "2024": 
      AK8PFPuppi: True

  apply_jec_msoftdrop_Data:
    2022_preEE:
      AK8PFPuppi: True
    2022_postEE: 
      AK8PFPuppi: True
    2023_preBPix: 
      AK8PFPuppi: True
    2023_postBPix: 
      AK8PFPuppi: True
    "2024": 
      AK8PFPuppi: True

  rescale_MET_config:
    2022_preEE:   
      apply: False
      MET_collection: "PuppiMET"
      Jet_collection: "Jet"
    2022_postEE:
      apply: False
      MET_collection: "PuppiMET"
      Jet_collection: "Jet"
    2023_preBPix:
      apply: False
      MET_collection: "PuppiMET"
      Jet_collection: "Jet"
    2023_postBPix:
      apply: False
      MET_collection: "PuppiMET"
      Jet_collection: "Jet"
  

