object_preselection:
  Muon:
    pt: 5.0
    eta: 2.4
    iso: 0.15  #PFIsoTight
    id: tightId

  Electron:
    pt: 15.0
    eta: 2.4
    iso: 0.06
    id: mvaIso_WP80

  Jet:
    dr_lepton: 0.4
    pt: 25.0
    eta: 2.5
    jetId: 2
    puId:
      wp: L
      value: 4
      maxpt: 50.0

  FatJet:
    pt: 300.0  #adapted for bbtautau run3 analysis
    eta: 2.4
    msd: 40.0
    jetId: 2
    nmu: 1
    #nsubjet: 2
    #nmusj: 1
    #dimuon_pt_ratio: 0.6
