plotting_style:
  #  labels_mc:
  #  TTHtoNon2B: "$t\\bar{t}$H(other)"

  samples_groups:
    "l":
      - QCD_MuEnriched__QCD_MuEnriched_l
      - TTto4Q__TTto4Q_l
      - SingleTop__SingleTop_l
      - VJets__VJets_l
      - SingleTop__SingleTop_l
    "c":
      - QCD_MuEnriched__QCD_MuEnriched_c
      - TTto4Q__TTto4Q_c
      - SingleTop__SingleTop_c
      - VJets__VJets_c
      - SingleTop__SingleTop_c
      - QCD_MuEnriched__QCD_MuEnriched_cc
      - TTto4Q__TTto4Q_cc
      - SingleTop__SingleTop_cc
      - VJets__VJets_cc
      - SingleTop__SingleTop_cc
    "b":
      - QCD_MuEnriched__QCD_MuEnriched_b
      - TTto4Q__TTto4Q_b
      - SingleTop__SingleTop_b
      - VJets__VJets_b
      - SingleTop__SingleTop_b
      - QCD_MuEnriched__QCD_MuEnriched_bb
      - TTto4Q__TTto4Q_bb
      - SingleTop__SingleTop_bb
      - VJets__VJets_bb
      - SingleTop__SingleTop_bb

  colors_mc:
    l: CMS_red
    c: CMS_orange
    b: CMS_blue

