scaleout: 200
chunksize: 400000
mem-per-worker: "8GB"
disk-per-worker: "8GB"
cores-per-worker: 1
adaptive: false
queue: "tomorrow"
walltime: "24:00:00"
performance-report: false
custom-setup-commands: null
conda-env: false
local-virtualenv: false
group-samples:
  # TTto4Q:
  #   - "TTto4Q"
  # Vjets:
  #   - "VJets"
  # SingleTop:
  #   - "SingleTop"

