HLT_triggers_prescales:
    2022_preEE:
        BTagMu:
          BTagMu_AK8DiJet170_Mu5 : 5
          BTagMu_AK8Jet170_DoubleMu5: 1
          BTagMu_AK8Jet300_Mu5: 1.2
          BTagMu_AK4Jet300_Mu5: 1
    2022_postEE:
        BTagMu:
          BTagMu_AK8DiJet170_Mu5 : 5
          BTagMu_AK8Jet170_DoubleMu5: 1
          BTagMu_AK8Jet300_Mu5: 1.2
          BTagMu_AK4Jet300_Mu5: 1
    2023_preBPix:
        BTagMu:
          BTagMu_AK8DiJet170_Mu5 : 12
          BTagMu_AK8Jet170_DoubleMu5: 1
          BTagMu_AK8Jet300_Mu5: 2
          BTagMu_AK4Jet300_Mu5: 1
    2023_postBPix:
        BTagMu:
          BTagMu_AK8DiJet170_Mu5 : 12
          BTagMu_AK8Jet170_DoubleMu5: 1
          BTagMu_AK8Jet300_Mu5: 2
          BTagMu_AK4Jet300_Mu5: 1
    # 2024:
    #     BTagMu:
    #       BTagMu_AK8DiJet170_Mu5 : 12
    #       BTagMu_AK8Jet170_DoubleMu5: 1
    #       BTagMu_AK8Jet300_Mu5: 2
    #       BTagMu_AK4Jet300_Mu5: 1
