HLT_triggers:
  "2016_PreVFP":
    BTagMu:
      - BTagMu_AK8Jet300_Mu5
      - BTagMu_AK4Jet300_Mu5
      - BTagMu_Jet300_Mu5
  "2016_PostVFP":
    BTagMu:
      - BTagMu_AK8Jet300_Mu5
      - BTagMu_AK4Jet300_Mu5
      - BTagMu_Jet300_Mu5
  "2017":
    BTagMu:
      - BTagMu_AK8Jet300_Mu5
      - BTagMu_AK4Jet300_Mu5
  "2018":
    BTagMu:
      - BTagMu_AK8Jet300_Mu5
      - BTagMu_AK4Jet300_Mu5
      - BTagMu_AK8Jet300_Mu5_noalgo
      - BTagMu_AK4Jet300_Mu5_noalgo
